spring:
  application:
    name: coongyapay
  task:
    scheduling:
      pool:
        size: 6

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

